sources:
  - name: walmart_databricks
    database: dmart
    schema: bronze
    tables:
      - name: orders
      - name: customers
      - name: employees
      - name: order_items
      - name: stores
      - name: products