sources:
  - name: dmart_Databrikcs
    database: dmart
    schema: bronze
    tables:
      - name: orders
      - name: customers
      - name: employees
      - name: orders_items
      - name: stores
      - name: products